# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2661f4d503e597b4724439a8663f3963b0f05f71b9d3da451fc2e69ee3f0d4ede815383b55f1e63fcd16ddf65bde60afdd9d4b7bd7252dfc12c6f71c7422fc7b

test:
  secret_key_base: 371268ba9a26b322ca8384109fbcf1d384077ba072dec0e93ae40a107d0cef22f96e0a1972eeb44f0e4c31d302c463935b7faf854c289d3f2dc0cf711d9cc377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
